### ISSUE TITLE
Feil i HTML-kode.

### ISSUE THREAD

**Issue by isakhauge** [isakhauge/WEB1100B_Company_Website_01_Responsive#5]
### Du må erstatte alle `&`-tegnene med `&amp;`.
**Se eksempel under:**

Fra dette:
`` ... Retail region Central & West Europe.<br>``

Til dette:
`` ... Retail region Central &amp; West Europe.<br>``

@KimPedersen91

**Comment by KimPedersen91** [comment]
Gjort om alle & til &amp;

**Comment by isakhauge** [comment]
Super!
